services:
  - type: web
    name: backend
    env: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: bash start_dev.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: mindspark_backend.settings
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        fromDatabase:
          name: quizai-db
          property: connectionString

databases:
  - name: quizai-db
    databaseName: quizai_database
    user: quizai_user
    plan: free

